feature: Add Patch3D operator
PyLops/pylops pull request #396
Opened 2022-05-30 13:56 UTC by mrava87

2022-06-02 20:22 UTC, mrava87 commented
@cako this is ready. It is a lot of code but I am not sure there is a better way to handle the various edges and corners. Have a look and let me know what you think :)

2022-06-03 05:11 UTC, cako commented
I'll have a look. Just a quick (and maybe dumb question), what is the difference between the Patch and Sliding operators?

2022-06-03 06:51 UTC, mrava87 commented
Thanks! No dumb at at, Sliding3D takes 1 full axis and windows over the other 2. Patch3D does take 3d windows all over the data. 

Just one practical example. For transforms like Radon that are almost invariant to the time axis (apart from edge effects) you can simply use the first, but for things like FKK that are not invariant to time axis you want to have small 3D windows :) makes sense?

2022-06-14 02:06 UTC, cako requested changes

2022-06-14 02:06 UTC, cako commented on pylops/utils/tapers.py
> +def tapernd(nmask, ntap, tapertype="hanning"):
Needs to be added to the docs

2022-06-14 09:00 UTC, mrava87 commented on examples/plot_patching.py
> +nop = (128, 128 // 2 + 1)  # second axis is real
Good point, done

2022-06-14 09:00 UTC, mrava87 commented on examples/plot_patching.py
> +nop = (128, 128, 128 // 2 + 1)  # second axis is real
Done

2022-06-14 09:05 UTC, mrava87 commented on examples/plot_patching.py
> +fig, axs = plt.subplots(1, 2, figsize=(7, 5), sharey=True)
Sure, makes sense, done now :)

2022-06-14 09:07 UTC, mrava87 commented on pylops/signalprocessing/Patch3D.py
> +       define such input parameter.
I think it makes lots of sense, I also always fail the first time and then use design=True to guide me. I am not just so sure how to do this as we dont really have any operator where things are not built directly when making the operator... maybe we could make a static method that can be called directly (prior to making the operator itself). What about you make a github issue so we dont forget and I can handle this on a separate PR?

2022-06-14 09:08 UTC, mrava87 commented on pylops/utils/tapers.py
> +def tapernd(nmask, ntap, tapertype="hanning"):
True!

2022-06-15 00:36 UTC, cako commented on pylops/signalprocessing/Patch3D.py
> +       define such input parameter.
Sure, let's do that!

2022-06-15 00:36 UTC, cako approved these changes

2022-06-15 05:11 UTC, merged